vich_uploader:
    db_driver: orm

    mappings:
       product:
            uri_prefix: uploads/images/products
            upload_destination: '%kernel.project_dir%/public/uploads/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
