#index:
#    path: /
#    controller: App\Controller\DefaultController::index
forum:
  path: /forum
  controller: App\Controller\ForumController::index

connexion:
  path: /connexion
  controller: App\Controller\SecurityController::login

inscription:
  path: /inscription
  controller: App\Controller\SecurityController::register